# Generated by Django 5.2 on 2025-04-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0002_alter_resume_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="education",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="experience",
            field=models.TextField(blank=True),
        ),
    ]
